services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:alpine"
    restart: unless-stopped
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD_SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/data/postgres
volumes:
  dbdata: