// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate a user with email and password and get access/refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful, tokens returned.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (invalid credentials or user not verified)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account and send an OTP for verification.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Registration successful. OTP has been sent to email.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                        }
                    },
                    "400": {
                        "description": "Bad Request (e.g., validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "409": {
                        "description": "Conflict (e.g., email already exists)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/auth/verify-otp": {
            "post": {
                "description": "Verify the OTP sent to the user's email and get access/refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "Verify OTP Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verification successful, tokens returned.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (e.g., invalid OTP, validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "Str0ngP@ssword"
                },
                "remember_me": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "Str0ngP@ssword"
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJI..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJI..."
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.VerifyOTPRequest": {
            "type": "object",
            "required": [
                "email",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_infra_response.Err": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "payload": {}
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_infra_response.Res": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "payload": {},
                "status_code": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Enter your bearer token in the format ` + "`" + `Bearer {token}` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Sea Catering API",
	Description:      "This is the API documentation for the Sea Catering application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
