// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google": {
            "get": {
                "description": "Redirect user to Google OAuth login page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Google OAuth Login",
                "responses": {
                    "303": {
                        "description": "Redirect to Google OAuth",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Callback endpoint for Google OAuth. Handles code and state from Google, then redirects to FE with tokens.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Google OAuth Callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Google",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth error",
                        "name": "error",
                        "in": "query"
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to FE with tokens",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate a user with email and password and get access/refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful, tokens returned.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (invalid credentials or user not verified)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Invalidate the refresh token and logout the user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Logout Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                        }
                    },
                    "400": {
                        "description": "Bad Request (validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (invalid or expired refresh token)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/auth/refresh-token": {
            "post": {
                "description": "Generate new access and refresh tokens using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refresh successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (invalid or expired refresh token)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account and send an OTP for verification.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Registration successful. OTP has been sent to email.",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                        }
                    },
                    "400": {
                        "description": "Bad Request (e.g., validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "409": {
                        "description": "Conflict (e.g., email already exists)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/auth/verify-otp": {
            "post": {
                "description": "Verify the OTP sent to the user's email and get access/refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "Verify OTP Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verification successful, tokens returned.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request (e.g., invalid OTP, validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/meal-plans/": {
            "get": {
                "description": "Get all meal plans.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MealPlan"
                ],
                "summary": "Get All Meal Plans",
                "responses": {
                    "200": {
                        "description": "Get all meal plans successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.MealPlanResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/meal-plans/{id}": {
            "get": {
                "description": "Get meal plan detail by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MealPlan"
                ],
                "summary": "Get Meal Plan By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get meal plan by ID successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.MealPlanResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid meal plan ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "404": {
                        "description": "Meal plan not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/subscriptions/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve all subscriptions for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Get User Subscriptions",
                "responses": {
                    "200": {
                        "description": "Get user subscriptions successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.SubscriptionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new meal plan subscription with payment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Create Subscription",
                "parameters": [
                    {
                        "description": "Create Subscription Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Subscription created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.PaymentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "404": {
                        "description": "Meal plan not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/subscriptions/webhook/midtrans": {
            "post": {
                "description": "Handle payment notification from Midtrans payment gateway. This endpoint is called by Midtrans to notify payment status changes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Handle Midtrans Webhook",
                "parameters": [
                    {
                        "description": "Midtrans Notification",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "order_id": {
                                    "type": "string"
                                },
                                "payment_type": {
                                    "type": "string"
                                },
                                "transaction_status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Webhook processed successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                        }
                    },
                    "400": {
                        "description": "Invalid notification data",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "404": {
                        "description": "Subscription not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permanently cancel a subscription. This action cannot be undone.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Cancel Subscription",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subscription cancelled successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.SubscriptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid subscription ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "403": {
                        "description": "Not authorized to cancel this subscription",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "404": {
                        "description": "Subscription not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}/pause": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Temporarily pause a subscription by specifying start and end dates. The subscription duration will be extended by the pause period.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Pause Subscription",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pause Subscription Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.PauseSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subscription paused successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.SubscriptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid subscription ID or request body",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid access token",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "403": {
                        "description": "Not authorized to pause this subscription",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "404": {
                        "description": "Subscription not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/testimonials/": {
            "get": {
                "description": "Get all testimonials.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Testimonial"
                ],
                "summary": "Get All Testimonials",
                "responses": {
                    "200": {
                        "description": "Get all testimonials successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.TestimonialResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new testimonial with photo upload. Only for authenticated users.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Testimonial"
                ],
                "summary": "Create Testimonial",
                "parameters": [
                    {
                        "type": "string",
                        "example": "John Doe",
                        "description": "Customer Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "The food was delicious",
                        "description": "Review Message",
                        "name": "message",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 5,
                        "description": "Rating (1-5)",
                        "name": "rating",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Photo of the meal",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Create testimonial successful",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                        }
                    },
                    "400": {
                        "description": "Bad Request (validation error)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        },
        "/users/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the authenticated user's profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Profile",
                "responses": {
                    "200": {
                        "description": "Get profile successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Res"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_infra_response.Err"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.CreateSubscriptionRequest": {
            "type": "object",
            "required": [
                "delivery_days",
                "meal_plan_id",
                "meal_types",
                "name",
                "phone_number"
            ],
            "properties": {
                "allergies": {
                    "type": "string",
                    "example": "Peanuts, Shellfish"
                },
                "delivery_days": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "monday",
                        "tuesday",
                        "wednesday"
                    ]
                },
                "meal_plan_id": {
                    "type": "string",
                    "example": "b3e1f8e2..."
                },
                "meal_types": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "breakfast",
                        "lunch"
                    ]
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "John Doe"
                },
                "phone_number": {
                    "type": "string",
                    "minLength": 10,
                    "example": "081234567890"
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "Str0ngP@ssword"
                },
                "remember_me": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJI..."
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.MealPlanResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "A healthy meal plan"
                },
                "id": {
                    "type": "string",
                    "example": "b3e1f8e2..."
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "photo_url": {
                    "type": "string",
                    "example": "https://..."
                },
                "price": {
                    "type": "number",
                    "example": 30000
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.PauseSubscriptionRequest": {
            "type": "object",
            "required": [
                "end_date",
                "start_date"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "2025-01-30"
                },
                "start_date": {
                    "type": "string",
                    "example": "2025-01-15"
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.PaymentResponse": {
            "type": "object",
            "properties": {
                "redirect_url": {
                    "type": "string",
                    "example": "https://app.sandbox.midtrans.com/snap/v3/redirection/66e4fa55..."
                },
                "token": {
                    "type": "string",
                    "example": "66e4fa55..."
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJI..."
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "Str0ngP@ssword"
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "allergies": {
                    "type": "string",
                    "example": "Peanuts, Shellfish"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-01-10"
                },
                "delivery_days": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "monday",
                        "tuesday",
                        "wednesday"
                    ]
                },
                "end_date": {
                    "type": "string",
                    "example": "2025-02-10"
                },
                "id": {
                    "type": "string",
                    "example": "b3e1f8e2..."
                },
                "meal_plan": {
                    "$ref": "#/definitions/github_com_Ablebil_sea-catering-be_internal_domain_dto.MealPlanResponse"
                },
                "meal_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "breakfast",
                        "lunch"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "pause_end_date": {
                    "type": "string",
                    "example": "2025-01-30"
                },
                "pause_start_date": {
                    "type": "string",
                    "example": "2025-01-15"
                },
                "phone_number": {
                    "type": "string",
                    "example": "08123456789"
                },
                "start_date": {
                    "type": "string",
                    "example": "2025-01-10"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "total_price": {
                    "type": "number",
                    "example": 180000
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.TestimonialResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "b3e1f8e2..."
                },
                "message": {
                    "type": "string",
                    "example": "The food was delicious"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "photo_url": {
                    "type": "string",
                    "example": "https://..."
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJI..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJI..."
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_domain_dto.VerifyOTPRequest": {
            "type": "object",
            "required": [
                "email",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_infra_response.Err": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "payload": {}
            }
        },
        "github_com_Ablebil_sea-catering-be_internal_infra_response.Res": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "payload": {},
                "status_code": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Enter your bearer token in the format ` + "`" + `Bearer {token}` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Sea Catering API",
	Description:      "This is the API documentation for the Sea Catering application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
